### ISSUE TITLE
Broken links in the resources documents

### ISSUE THREAD

**Issue by ftessier** [a-cosmology-group/acg#4]
The following links on the [Resources page](https://github.com/a-cosmology-group/acg/tree/main/resources) are broken. They ought to be updated or removed.

https://github.com/a-cosmology-group/acg/blob/694ed3fa59a2f399bdd55cac316d6ecbde7c2d30/resources/README.md?plain=1#L31

https://github.com/a-cosmology-group/acg/blob/694ed3fa59a2f399bdd55cac316d6ecbde7c2d30/resources/README.md?plain=1#L47

https://github.com/a-cosmology-group/acg/blob/694ed3fa59a2f399bdd55cac316d6ecbde7c2d30/resources/README.md?plain=1#L55

**Comment by marmetl** [comment]
Line 31, the website has changed its structure.  The link is now
https://ec.europa.eu/research-and-innovation/en/horizon-magazine/dark-energy-biggest-mystery-cosmology-it-may-not-exist-all-leading-physicist

Line 47, David Dilworth's website is down but the link should work when the site comes back on line.  Can we leave the link as is? I guess not because GitHub will keep reporting it as an error...  How about:
Astrophysicists, References and Websites, https://cosmologyscience.com/ref.htm<br>
so the link is always there and GitHub doesn't complain.  We would have to re-visit this later to enable the link when David's website is back online...

Line 55, the website has changed its structure, the link is now:
https://nautil.us/do-we-have-the-big-bang-theory-all-wrong-234989/

Could I have done these fix myself on your 'branch'?

**Comment by marmetl** [comment]
Two links corrected, 3rd one left as is with a warning that the site is down.
What would you do about a dead link that is supposed to come back to life? Is there a ToDo list on GitHub I can use?
